fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: c4e8435b673b0c51918007429309bf9d3cbca904 # v2.13.2
    hooks:
      - id: golangci-lint-full
        language_version: 1.27.0
        stages: [pre-commit]
      - id: golangci-lint-fmt
        language_version: 1.27.0
        stages: [pre-commit]
