//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcknowledgedViolationRecord) DeepCopyInto(out *AcknowledgedViolationRecord) {
	*out = *in
	in.Violation.DeepCopyInto(&out.Violation)
	in.AcknowledgedAt.DeepCopyInto(&out.AcknowledgedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcknowledgedViolationRecord.
func (in *AcknowledgedViolationRecord) DeepCopy() *AcknowledgedViolationRecord {
	if in == nil {
		return nil
	}
	out := new(AcknowledgedViolationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPolicyRule) DeepCopyInto(out *IstioAuthorizationPolicyRule) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]IstioFrom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]IstioTo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPolicyRule.
func (in *IstioAuthorizationPolicyRule) DeepCopy() *IstioAuthorizationPolicyRule {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPolicySpec) DeepCopyInto(out *IstioAuthorizationPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]IstioAuthorizationPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPolicySpec.
func (in *IstioAuthorizationPolicySpec) DeepCopy() *IstioAuthorizationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioFrom) DeepCopyInto(out *IstioFrom) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioFrom.
func (in *IstioFrom) DeepCopy() *IstioFrom {
	if in == nil {
		return nil
	}
	out := new(IstioFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioOperation) DeepCopyInto(out *IstioOperation) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioOperation.
func (in *IstioOperation) DeepCopy() *IstioOperation {
	if in == nil {
		return nil
	}
	out := new(IstioOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSource) DeepCopyInto(out *IstioSource) {
	*out = *in
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSource.
func (in *IstioSource) DeepCopy() *IstioSource {
	if in == nil {
		return nil
	}
	out := new(IstioSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioTo) DeepCopyInto(out *IstioTo) {
	*out = *in
	in.Operation.DeepCopyInto(&out.Operation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioTo.
func (in *IstioTo) DeepCopy() *IstioTo {
	if in == nil {
		return nil
	}
	out := new(IstioTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBackendSpec) DeepCopyInto(out *PolicyBackendSpec) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(v1.NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(IstioAuthorizationPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBackendSpec.
func (in *PolicyBackendSpec) DeepCopy() *PolicyBackendSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViolationInfo) DeepCopyInto(out *ViolationInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Source.DeepCopyInto(&out.Source)
	in.Dest.DeepCopyInto(&out.Dest)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViolationInfo.
func (in *ViolationInfo) DeepCopy() *ViolationInfo {
	if in == nil {
		return nil
	}
	out := new(ViolationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViolationRecord) DeepCopyInto(out *ViolationRecord) {
	*out = *in
	in.ViolationInfo.DeepCopyInto(&out.ViolationInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViolationRecord.
func (in *ViolationRecord) DeepCopy() *ViolationRecord {
	if in == nil {
		return nil
	}
	out := new(ViolationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViolationRecordKey) DeepCopyInto(out *ViolationRecordKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViolationRecordKey.
func (in *ViolationRecordKey) DeepCopy() *ViolationRecordKey {
	if in == nil {
		return nil
	}
	out := new(ViolationRecordKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicy) DeepCopyInto(out *WorkloadNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicy.
func (in *WorkloadNetworkPolicy) DeepCopy() *WorkloadNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyList) DeepCopyInto(out *WorkloadNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyList.
func (in *WorkloadNetworkPolicyList) DeepCopy() *WorkloadNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposal) DeepCopyInto(out *WorkloadNetworkPolicyProposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposal.
func (in *WorkloadNetworkPolicyProposal) DeepCopy() *WorkloadNetworkPolicyProposal {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyProposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposalList) DeepCopyInto(out *WorkloadNetworkPolicyProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkPolicyProposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposalList.
func (in *WorkloadNetworkPolicyProposalList) DeepCopy() *WorkloadNetworkPolicyProposalList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkPolicyProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposalSpec) DeepCopyInto(out *WorkloadNetworkPolicyProposalSpec) {
	*out = *in
	in.PolicyBackendSpec.DeepCopyInto(&out.PolicyBackendSpec)
	out.WorkloadTargetingSpec = in.WorkloadTargetingSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposalSpec.
func (in *WorkloadNetworkPolicyProposalSpec) DeepCopy() *WorkloadNetworkPolicyProposalSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyProposalStatus) DeepCopyInto(out *WorkloadNetworkPolicyProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyProposalStatus.
func (in *WorkloadNetworkPolicyProposalStatus) DeepCopy() *WorkloadNetworkPolicyProposalStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicySpec) DeepCopyInto(out *WorkloadNetworkPolicySpec) {
	*out = *in
	in.PolicyBackendSpec.DeepCopyInto(&out.PolicyBackendSpec)
	out.WorkloadTargetingSpec = in.WorkloadTargetingSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicySpec.
func (in *WorkloadNetworkPolicySpec) DeepCopy() *WorkloadNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkPolicyStatus) DeepCopyInto(out *WorkloadNetworkPolicyStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]ViolationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcknowledgedViolations != nil {
		in, out := &in.AcknowledgedViolations, &out.AcknowledgedViolations
		*out = make([]AcknowledgedViolationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkPolicyStatus.
func (in *WorkloadNetworkPolicyStatus) DeepCopy() *WorkloadNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTargetRef) DeepCopyInto(out *WorkloadTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTargetRef.
func (in *WorkloadTargetRef) DeepCopy() *WorkloadTargetRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTargetingSpec) DeepCopyInto(out *WorkloadTargetingSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTargetingSpec.
func (in *WorkloadTargetingSpec) DeepCopy() *WorkloadTargetingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadTargetingSpec)
	in.DeepCopyInto(out)
	return out
}
