apiVersion: networkenforcer.kubewarden.io/v1alpha1
kind: WorkloadNetworkPolicy
metadata:
  name: networkpolicy-sample
spec:
  mode: protect
  backend: kubernetes
  targetRef:
    kind: Deployment
    name: nginx
  direction: Ingress
  kubernetes:
    podSelector:
      matchLabels:
        app: nginx
    policyTypes:
      - Ingress
    ingress:
      - from:
          - podSelector: {}
