apiVersion: networkenforcer.kubewarden.io/v1alpha1
kind: WorkloadNetworkPolicyProposal
metadata:
  name: deployment-nginx-deployment-ingress
spec:
  backend: kubernetes
  targetRef:
    kind: Deployment
    name: nginx-deployment
  direction: Ingress
  kubernetes:
    podSelector:
      matchLabels:
        app: nginx
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: default
        podSelector:
          matchLabels:
            app: ubuntu
      ports:
      - port: 80
        protocol: TCP
