apiVersion: security.kubewarden.io/v1alpha1
kind: WorkloadNetworkPolicy
metadata:
  name: networkpolicy-sample
spec:
  mode: protect
  backend: kubernetes
  kubernetes:
    podSelector:
      matchLabels:
        app: nginx
    policyTypes:
      - Ingress
      - Egress
    ingress:
      - from:
          - podSelector: {}
    egress:
      - to:
          - podSelector: {}
