name: Build, Sign, and Generate SBOM, Attestation & Provenance

on:
  workflow_call:
    inputs:
      version:
        type: string

  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        component: [controller]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write    # Push images to ghcr.io
      id-token: write    # Sign images with cosign (OIDC)
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build image
        uses: rancher-sandbox/runtime-enforcer/.github/actions/container-build@07468d7766cb968bda11455a4b7903acfb2a72bd
        with:
          arch: ${{ matrix.arch }}
          dockerfile: package/Dockerfile.${{ matrix.component }}
          image: ${{ matrix.component }}
          repo: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        component: [controller]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Merge images
        uses: rancher-sandbox/runtime-enforcer/.github/actions/merge-multiarch@a3d9b9e3c9953f5100eddb094cffdcede3c1e770
        with:
          arch: amd64,arm64
          image: ${{ matrix.component }}
          repo: ${{ github.repository }}
          tag: ${{ inputs.version || 'latest' }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
